package frc.robot.subsystems.drive;

import static edu.wpi.first.units.Units.Inches;
import static edu.wpi.first.units.Units.Meters;
import static edu.wpi.first.units.Units.MetersPerSecond;
import static edu.wpi.first.units.Units.Pounds;
import static edu.wpi.first.units.Units.Second;
import static edu.wpi.first.units.Units.Seconds;
import static edu.wpi.first.units.Units.Volts;

import java.util.List;
import java.util.HashMap;
import java.util.Optional;
import java.util.function.Supplier;

import org.ironmaple.simulation.SimulatedArena;
import org.ironmaple.simulation.seasonspecific.rebuilt2026.Arena2026Rebuilt;
import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;

import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.config.PIDConstants;
import com.pathplanner.lib.config.RobotConfig;
import com.pathplanner.lib.controllers.PPHolonomicDriveController;
import com.pathplanner.lib.path.GoalEndState;
import com.pathplanner.lib.path.PathConstraints;
import com.pathplanner.lib.path.PathPlannerPath;
import com.pathplanner.lib.path.Waypoint;
import com.pathplanner.lib.commands.FollowPathCommand;


import java.util.Optional;
import java.util.function.Supplier;

import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.controller.PIDController;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.math.system.plant.DCMotor;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import frc.robot.Constants.FieldLayout;
import frc.robot.Constants.LimelightConstants;
import frc.robot.Robot;
import frc.robot.generated.TunerConstants;
import frc.robot.generated.TunerConstants.TunerSwerveDrivetrain;
import frc.robot.shotlib.ChassisAccelerations;
import frc.robot.vision.LimelightHelpers;
import frc.robot.vision.LimelightHelpers.PoseEstimate;
import frc.robot.vision.VisionAcceptor;
import frc.robot.utils.simulation.MapleSimSwerveDrivetrain;
import dev.doglog.DogLog;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {
    private static final double kSimLoopPeriod = 0.004; // 4 ms
    private Notifier m_simNotifier = null;

    public ChassisSpeeds m_previousSpeed = new ChassisSpeeds(0, 0, 0);
    private ChassisSpeeds prevFieldRelVelocities = new ChassisSpeeds();

    private MapleSimSwerveDrivetrain mapleSimSwerveDrivetrain = null;

    public Rotation2d m_gyroOffset = new Rotation2d();

    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;

    private final SwerveRequest.ApplyRobotSpeeds m_pathApplyRobotSpeeds = new SwerveRequest.ApplyRobotSpeeds();

    // /* Swerve requests to apply during SysId characterization */
    // private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization = new SwerveRequest.SysIdSwerveTranslation();
    // private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization = new SwerveRequest.SysIdSwerveSteerGains();
    // private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization = new SwerveRequest.SysIdSwerveRotation();

    VisionAcceptor visionAcceptorLeft = new VisionAcceptor(true);
    VisionAcceptor visionAcceptorRight = new VisionAcceptor(true);
    VisionAcceptor visionAcceptorShooter = new VisionAcceptor(false);

    HashMap<String,Pose2d> previousPositions = new HashMap<>();

    /* SysId routine for characterizing translation. This is used to find PID gains for the drive motors. */
//     private final SysIdRoutine m_sysIdRoutineTranslation = new SysIdRoutine(
//     new SysIdRoutine.Config(
//         null,
//         Volts.of(3),
//         Seconds.of(5),
//         state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())
//     ),
//     new SysIdRoutine.Mechanism(
//         output -> setControl(m_translationCharacterization.withVolts(output)),
//         log -> {
//             var driveMotor = getModule(0).getDriveMotor(); // front left, CAN ID 22

//             double positionMeters = driveMotor.getPosition().getValueAsDouble()
//                 * (2.0 * Math.PI * TunerConstants.kWheelRadius.in(Meters))
//                 / TunerConstants.kDriveGearRatio;

//             double velocityMetersPerSec = driveMotor.getVelocity().getValueAsDouble()
//                 * (2.0 * Math.PI * TunerConstants.kWheelRadius.in(Meters))
//                 / TunerConstants.kDriveGearRatio;

//             log.motor("drive-front-left")
//                 .voltage(Volts.of(driveMotor.getMotorVoltage().getValueAsDouble()))
//                 .linearPosition(Meters.of(positionMeters))
//                 .linearVelocity(MetersPerSecond.of(velocityMetersPerSec));
//         },
//         this
//     )
// );

    /* SysId routine for characterizing steer. This is used to find PID gains for the steer motors. */
    // private final SysIdRoutine m_sysIdRoutineSteer = new SysIdRoutine(
    //     new SysIdRoutine.Config(
    //         null,        // Use default ramp rate (1 V/s)
    //         Volts.of(7), // Use dynamic voltage of 7 V
    //         null,        // Use default timeout (10 s)
    //         // Log state with SignalLogger class
    //         state -> SignalLogger.writeString("SysIdSteer_State", state.toString())
    //     ),
    //     new SysIdRoutine.Mechanism(
    //         volts -> setControl(m_steerCharacterization.withVolts(volts)),
    //         null,
    //         this
    //     )
    // );

    /*
     * SysId routine for characterizing rotation.
     * This is used to find PID gains for the FieldCentricFacingAngle HeadingController.
     * See the documentation of SwerveRequest.SysIdSwerveRotation for info on importing the log to SysId.
     */
    // private final SysIdRoutine m_sysIdRoutineRotation = new SysIdRoutine(
    //     new SysIdRoutine.Config(
    //         /* This is in radians per second², but SysId only supports "volts per second" */
    //         Volts.of(Math.PI / 6).per(Second),
    //         /* This is in radians per second, but SysId only supports "volts" */
    //         Volts.of(Math.PI),
    //         null, // Use default timeout (10 s)
    //         // Log state with SignalLogger class
    //         state -> SignalLogger.writeString("SysIdRotation_State", state.toString())
    //     ),
    //     new SysIdRoutine.Mechanism(
    //         output -> {
    //             /* output is actually radians per second, but SysId only supports "volts" */
    //             setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
    //             /* also log the requested output for SysId */
    //             SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
    //         },
    //         null,
    //         this
    //     )
    // );

    /* The SysId routine to test */
    // private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants   Drivetrain-wide constants for the swerve drive
     * @param modules               Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
    }
    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency The frequency to run the odometry loop. If
     *                                unspecified or set to 0 Hz, this is 250 Hz on
     *                                CAN FD, and 100 Hz on CAN 2.0.
     * @param modules                 Constants for each specific module
     */

    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        SwerveModuleConstants<?, ?, ?>... modules) {
    super(
            drivetrainConstants,
            odometryUpdateFrequency,
            // modules
            MapleSimSwerveDrivetrain.regulateModuleConstantsForSimulation(modules));
    if (Utils.isSimulation()) {
        startSimThread();
    }
}
    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants       Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
     *                                  unspecified or set to 0 Hz, this is 250 Hz on
     *                                  CAN FD, and 100 Hz on CAN 2.0.
     * @param odometryStandardDeviation The standard deviation for odometry calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param visionStandardDeviation   The standard deviation for vision calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param modules                   Constants for each specific module
     */
    
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        Matrix<N3, N1> odometryStandardDeviation,
        Matrix<N3, N1> visionStandardDeviation,
        SwerveModuleConstants<?, ?, ?>... modules) {
    super(
            drivetrainConstants,
            odometryUpdateFrequency,
            odometryStandardDeviation,
            visionStandardDeviation,
            // modules
            MapleSimSwerveDrivetrain.regulateModuleConstantsForSimulation(modules));
    if (Utils.isSimulation()) {
        startSimThread();
    }
}

    public void configureAutoBuilder() {
         try {
            var config = RobotConfig.fromGUISettings();
            AutoBuilder.configure(
                () -> getState().Pose,   // Supplier of current robot pose
                this::resetPose,         // Consumer for seeding pose against auto
                () -> getState().Speeds, // Supplier of current robot speeds
                // Consumer of ChassisSpeeds and feedforwards to drive the robot
                (speeds, feedforwards) -> setControl(
                    m_pathApplyRobotSpeeds.withSpeeds(ChassisSpeeds.discretize(speeds, 0.020))
                        .withWheelForceFeedforwardsX(feedforwards.robotRelativeForcesXNewtons())
                        .withWheelForceFeedforwardsY(feedforwards.robotRelativeForcesYNewtons())
                ),
                new PPHolonomicDriveController(
                    // PID constants for translation
                    new PIDConstants(1.13, 0, 0), //prev 10
                    // PID constants for rotation
                    new PIDConstants(1.13, 0, 0) //prev 7
                ),
                config,
                // Assume the path needs to be flipped for Red vs Blue, this is normally the case
                () -> DriverStation.getAlliance().orElse(Alliance.Blue) == Alliance.Red,
                this // Subsystem for requirements
            );
        } catch (Exception ex) {
            DriverStation.reportError("Failed to load PathPlanner config and configure AutoBuilder", ex.getStackTrace());
        }

        // Create a list of waypoints from poses. Each pose represents one waypoint.
        // The rotation component of the pose should be the direction of travel. Do not
        // use holonomic rotation.
        // List<Waypoint> waypoints = PathPlannerPath.waypointsFromPoses(
        //         new Pose2d(1.0, 1.0, Rotation2d.fromDegrees(0)),
        //         new Pose2d(3.0, 1.0, Rotation2d.fromDegrees(0)),
        //         new Pose2d(5.0, 3.0, Rotation2d.fromDegrees(90)));

        // PathConstraints constraints = new PathConstraints(3.0, 3.0, 2 * Math.PI, 4 * Math.PI); // The constraints for
                                                                                               // this path.
        // PathConstraints constraints = PathConstraints.unlimitedConstraints(12.0); //
        // You can also use unlimited constraints, only limited by motor torque and
        // nominal battery voltage

        // Create the path using the waypoints created above
        // PathPlannerPath path = new PathPlannerPath(
        //         waypoints,
        //         constraints,
        //         null, // The ideal starting state, this is only relevant for pre-planned paths, so can
        //               // be null for on-the-fly paths.
        //         new GoalEndState(0.0, Rotation2d.fromDegrees(-90)) // Goal end state. You can set a holonomic rotation
        //                                                            // here. If using a differential drivetrain, the
        //                                                            // rotation will have no effect.
        // );

        // Prevent the path from being flipped if the coordinates are already correct
        // path.preventFlipping = true;
    }


    /**
     * Returns a command that applies the specified control request to this swerve drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */
    public Command applyRequest(Supplier<SwerveRequest> request) {
        return run(() -> this.setControl(request.get()));
    }

    /**
     * Runs the SysId Quasistatic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    // public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
    //     return m_sysIdRoutineToApply.quasistatic(direction);
    // }

    /**
     * Runs the SysId Dynamic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Dynamic test
     * @return Command to run
     */
    // public Command sysIdDynamic(SysIdRoutine.Direction direction) {
    //     return m_sysIdRoutineToApply.dynamic(direction);
    // }

    @Override
    public void periodic() {
        /*
         * Periodically try to apply the operator perspective.
         * If we haven't applied the operator perspective before, then we should apply
         * it regardless of DS state.
         * This allows us to correct the perspective in case the robot code restarts
         * mid-match.
         * Otherwise, only check and apply the operator perspective if the DS is
         * disabled.
         * This ensures driving behavior doesn't change until an explicit disable event
         * occurs during testing.
         */

        if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
            DriverStation.getAlliance().ifPresent(allianceColor -> {
                setOperatorPerspectiveForward(
                        allianceColor == Alliance.Red
                                ? kRedAlliancePerspectiveRotation
                                : kBlueAlliancePerspectiveRotation);
                m_hasAppliedOperatorPerspective = true;
            });
        }

        DogLog.log("BatteryVoltage", RobotController.getBatteryVoltage());
        
        // =====================================================
        // Add this back in after match66
        
        LimelightHelpers.SetRobotOrientation(LimelightConstants.SHOOTER_LIMELIGHT, getAngle(), 0, 0, 0, 0, 0);
        LimelightHelpers.SetRobotOrientation(LimelightConstants.LEFT_LIMELIGHT, getAngle(), 0, 0, 0, 0, 0);
        boolean gyroWasAccepted = false;
        
        if (getState().Pose != null) {
            // Fetch ONCE, use the result for both accept and update

            PoseEstimate shooterEstimate = LimelightHelpers.getBotPoseEstimate_wpiBlue(LimelightConstants.SHOOTER_LIMELIGHT);
            PoseEstimate lefEstimate = LimelightHelpers.getBotPoseEstimate_wpiBlue(LimelightConstants.LEFT_LIMELIGHT);
            
            processVision(visionAcceptorShooter, LimelightConstants.SHOOTER_LIMELIGHT);
            processVision(visionAcceptorLeft, LimelightConstants.LEFT_LIMELIGHT);
            if (acceptGyro(visionAcceptorShooter, shooterEstimate)) {
                resetGyro(shooterEstimate);
                gyroWasAccepted = true;
            }
            if ((!gyroWasAccepted) && acceptGyro(visionAcceptorLeft, lefEstimate)) {
                resetGyro(lefEstimate);
                gyroWasAccepted = true;
            }
        // ===========================================================

        // DogLog.log("Drive/OdometryPose", getState().Pose);
        // DogLog.log("Drive/TargetStates", getState().ModuleTargets);
        // DogLog.log("Drive/MeasuredStates", getState().ModuleStates);
        // DogLog.log("Drive/MeasuredSpeeds", getState().Speeds);

        
        DogLog.log("pose/distancefromhub", getAbsouluteDistanceFromHub());
        DogLog.log("pose/anglefromhub", getAbsoluteAngleFromHub());
        DogLog.log("pose/X", getState().Pose.getX());
        DogLog.log("pose/Y", getState().Pose.getY());
        DogLog.log("pose/Rotation", getState().Pose.getRotation().getDegrees());
        }
    }
        // if(mapleSimSwerveDrivetrain != null) {
            // DogLog.log("Drive/SimulationPose",
            // mapleSimSwerveDrivetrain.mapleSimDrive.getSimulatedDriveTrainPose());
            // }
    // }

    public MapleSimSwerveDrivetrain getSimulationDriveTrain() {
        return mapleSimSwerveDrivetrain;
    }

    private void startSimThread() {
        // m_lastSimTime = Utils.getCurrentTimeSeconds();

        // /* Run simulation at a faster rate so PID gains behave more reasonably */
        // m_simNotifier = new Notifier(() -> {
        //     final double currentTime = Utils.getCurrentTimeSeconds();
        //     double deltaTime = currentTime - m_lastSimTime;
        //     m_lastSimTime = currentTime;

        //     /* use the measured time delta, get battery voltage from WPILib */
        //     updateSimState(deltaTime, RobotController.getBatteryVoltage());
        // });
        // m_simNotifier.startPeriodic(kSimLoopPeriod);

        SimulatedArena.overrideInstance(new Arena2026Rebuilt(false));

        mapleSimSwerveDrivetrain = new MapleSimSwerveDrivetrain(
            Seconds.of(kSimLoopPeriod),
            // TODO: modify the following constants according to your robot
            Pounds.of(100), // robot weight
            Inches.of(30.5), // bumper length
            Inches.of(30.5), // bumper width
            DCMotor.getKrakenX60(4), // drive motor type
            DCMotor.getFalcon500(4), // steer motor type
            2.225, // wheel COF
            getModuleLocations(),
            getPigeon2(),
            getModules(),
            TunerConstants.FrontLeft,
            TunerConstants.FrontRight,
            TunerConstants.BackLeft,
            TunerConstants.BackRight);

    
      /* Run simulation at a faster rate so PID gains behave more reasonably */
    m_simNotifier = new Notifier(mapleSimSwerveDrivetrain::update);
    m_simNotifier.startPeriodic(kSimLoopPeriod);
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     */
    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     * <p>
     * Note that the vision measurement standard deviations passed into this method
     * will continue to apply to future measurements until a subsequent call to
     * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     * @param visionMeasurementStdDevs Standard deviations of the vision pose measurement
     *     in the form [x, y, theta]ᵀ, with units in meters and radians.
     */
    @Override
    public void addVisionMeasurement(
        Pose2d visionRobotPoseMeters,
        double timestampSeconds,
        Matrix<N3, N1> visionMeasurementStdDevs
    ) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds), visionMeasurementStdDevs);
    }

    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param timestampSeconds The timestamp of the pose in seconds.
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is empty).
     */
    @Override
    public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
    }
    // @Override
    // public void resetPose(Pose2d pose) {
    //     if (this.mapleSimSwerveDrivetrain != null)
    //         mapleSimSwerveDrivetrain.mapleSimDrive.setSimulationWorldPose(pose);
    //     Timer.delay(0.05); // Wait for simulation to update
    //     super.resetPose(pose);
    // }

    public Pose2d getPose() {
        if (getState().Pose != null) {
        return getState().Pose;
        }
        return new Pose2d(0, 0, new Rotation2d(0));
    }

    public double getAngle() {
        double angle = ((getState().Pose.getRotation().getDegrees()));
        if (getState().Pose != null) {
            if (angle < 0) {
                angle += 360;
            }
            return angle;
        }
        return 0;
    }

    public double getRadians() {
        if (getState().Pose != null) {
        return Math.toRadians(getAngle());
        }
        return 0;
    }

    public ChassisAccelerations getAccelerations() {
        if (getState() != null) {
        ChassisAccelerations chassisAccelerations = new ChassisAccelerations(getState().Speeds, m_previousSpeed, 0.02);
        m_previousSpeed = getState().Speeds;
        return chassisAccelerations;
        }
        return new ChassisAccelerations(0, 0, 0);
    }

    public ChassisSpeeds getFieldRelativeSpeeds() {
        if (getState() != null) {
         ChassisSpeeds fieldRelativeSpeeds = ChassisSpeeds.fromRobotRelativeSpeeds(getState().Speeds, getState().Pose.getRotation());
         prevFieldRelVelocities = fieldRelativeSpeeds;
         return fieldRelativeSpeeds;
        }
        return new ChassisSpeeds(0, 0, 0);
    }

    public ChassisAccelerations getFieldRelativeAccelerations() {
        if (getState() != null) {
        return new ChassisAccelerations(getFieldRelativeSpeeds(), prevFieldRelVelocities, 0.020);
        }
        return new ChassisAccelerations(new ChassisSpeeds(0, 0, 0), new ChassisSpeeds(0,0,0), 0);
    }


    // _______________________________________ Vision Code _______________________________________

    public boolean acceptVision(VisionAcceptor acceptor, String name) {
        boolean acceptVisionMeasurement = false;
        PoseEstimate currentPose = LimelightHelpers.getBotPoseEstimate_wpiBlue_MegaTag2(name);
        if (currentPose != null) {
        acceptVisionMeasurement = acceptor.shouldAccept(currentPose.pose, previousPositions.get(name), getState().Speeds);
        previousPositions.put(name, currentPose.pose);
        }
        return acceptVisionMeasurement;
    }
    public void updateVision(String name) {
        PoseEstimate currentPose = LimelightHelpers.getBotPoseEstimate_wpiBlue_MegaTag2(name);
        if (currentPose != null) {
            addVisionMeasurement(currentPose.pose, Utils.currentTimeToFPGATime(currentPose.timestampSeconds));
        }
    }

    private PoseEstimate processVision(VisionAcceptor acceptor, String name) {
    PoseEstimate estimate = LimelightHelpers.getBotPoseEstimate_wpiBlue_MegaTag2(name);
    if (estimate == null) return null;
    
    boolean accepted = acceptor.shouldAccept(estimate.pose, previousPositions.get(name), getState().Speeds);
    previousPositions.put(name, estimate.pose);
    //  SmartDashboard.putBoolean("pose/Accept" + name, accepted);
    
    if (accepted) {
        addVisionMeasurement(estimate.pose, (estimate.timestampSeconds));
    }
    return estimate;
}

    public boolean acceptGyro(VisionAcceptor acceptor, PoseEstimate estimate) {
        return acceptor.shouldResetGyro() && estimate != null && estimate.tagCount > 0;
    }

    public void resetGyro(PoseEstimate estimate) {
    // public void resetGyro(String name) {
        // Rotation2d limelightAngle = LimelightHelpers.getBotPose2d_wpiBlue(name).getRotation();
        // Rotation2d correctedAngleOffset = new Rotation2d(limelightAngle.getRadians() - getRadians());
        // m_gyroOffset = correctedAngleOffset;
        // Rotation2d correctAngle = new Rotation2d(getRadians() + correctedAngleOffset.getRadians());
        // resetRotation(correctAngle);
        if (estimate == null) return;
        resetRotation(estimate.pose.getRotation());
        }
    


    public double getTurnToSpeakerSpeed(PIDController turnPidController) {
        double angleFromSpeaker = getAbsoluteAngleFromHub();
        double rz = getAngle();
        rz = rz < 0 ? rz + 360 : rz;
        double speed = -(turnPidController.calculate(angleFromSpeaker - rz));
        return speed;
    }

    public double getAbsoluteAngleFromHub() {
        // double[] botPose = getBotPose();
        // double rX = getBotPoseValue(botPose, 0);
        // double rY = getBotPoseValue(botPose, 1);
        double rX = getPose().getX();
        double rY = getPose().getY();

        if (Robot.getAllianceColor() == DriverStation.Alliance.Blue) {
            return Math.toDegrees(
                    Math.atan2(rY - FieldLayout.CENTER_OF_HUB_BLUE.getY(), rX - FieldLayout.CENTER_OF_HUB_BLUE.getX()));
                    // + 180;
        } else {
            return Math.toDegrees(
                    Math.atan2(rY - FieldLayout.CENTER_OF_HUB_RED.getY(), rX - FieldLayout.CENTER_OF_HUB_RED.getX()));
                    // + 180;
        }
    }

    public double getAbsouluteDistanceFromHub() {
        double rX = getPose().getX();
        double rY = getPose().getY();
        double tX;
        double tY;
        // double tAngle = getAbsoluteAngleFromHub();
        if (Robot.getAllianceColor() == Alliance.Blue) {
            tX = FieldLayout.CENTER_OF_HUB_BLUE.getX();
            tY = FieldLayout.CENTER_OF_HUB_BLUE.getY();
        } else {
            tX = FieldLayout.CENTER_OF_HUB_RED.getX();
            tY = FieldLayout.CENTER_OF_HUB_RED.getY();
        }
        // double adjacent = rX - tX;
        double distanceFromHub = Math.hypot(rX - tX, rY - tY); // hypotenuse = adjacent /
                                                                                     // cos(angle)

        return distanceFromHub;
    }
}
